#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GIT_EMAIL=$(git config user.email)
DOMAIN="@pxlp.dev"

if [[ "$GIT_EMAIL" == *"$DOMAIN"* ]]; then
  echo "PXLP email is used"
else
  echo "please use your PXLP email to commit changes"
  exit 1
fi

yarn lint
yarn typecheck
